apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 2  # Number of pod instances
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: drillo-app
        image: 1010varun/major_project:v1
        ports:
          - containerPort: 8000
        imagePullPolicy: IfNotPresent
